teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: joy_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.5
      -
        axis: 0
        target: angular.z
        scale: 0.5

  joy_priority:
    type: service
    service_name: /mux/select
    buttons: [0]
    service_request:
      topic: joy_vel

  key_priority:
    type: service
    service_name: /mux/select
    buttons: [1]
    service_request:
      topic: key_vel

  nav_priority:
    type: service
    service_name: /mux/select
    buttons: [2]
    service_request:
      topic: nav_vel

  no_priority:
    type: service
    service_name: /mux/select
    buttons: [3]
    service_request:
      topic: __none
